import "./globals.scss";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { cormorant_Garamond, caveat } from "@/fonts";
import AuthProvider from "../context/AuthProvider";
import ToasterContext from "../context/ToasterContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cormorant_Garamond.variable} ${caveat.variable}`}>
        <AuthProvider>
          <ToasterContext />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
